### ISSUE TITLE
This probably isn't a issue but i want to know if would be possible add fever 1 and 2 support.

### ISSUE THREAD

**Issue by ramdompersom** [nickworonekin/puyo-text-editor#3]

**Comment by nickworonekin** [comment]
While this would be a nice feature to add, there aren't any plans to add support for Fever 1 and Fever 2 at the current time.

Fever 1 support would be a bit of a pain as the text is hard-coded within the game's executable, making it challenging if not outright impossible to replace any text lines that exceeds the number of characters in the original text line.

Fever 2 support is a little less challenging, but text is stored in multiple MOT files which do contain more than just text.
