### ISSUE TITLE
cnvrs-text from Sonic Frontiers Support

### ISSUE THREAD

**Issue by Damin72** [nickworonekin/puyo-text-editor#6]
Strange situation with this game. Some files opens, some not. =/
Here an examples working (fishing/CyberSpace) and not working (others).
[Text.zip](https://github.com/nickworonekin/puyo-text-editor/files/9931262/Text.zip)

**Comment by ricky-daniel13** [comment]
Apparently Frontiers cnvrs-text files use a new fourth value for text-aligment (3). Since the program only expects one to three when building the xml, it breaks.
Adding a fourth enum to CnvrsTextTextAligment.cs with value 3 seems to fix the issue. I've tried it with at least 20 files from text_caption_es.

**Comment by breakthetargets** [comment]
> Apparently Frontiers cnvrs-text files use a new fourth value for text-aligment (3). Since the program only expects one to three when building the xml, it breaks. Adding a fourth enum to CnvrsTextTextAligment.cs with value 3 seems to fix the issue. I've tried it with at least 20 files from text_caption_es.

Can confirm that this works, thanks for the heads up.

**Comment by nickworonekin** [comment]
This fourth value for text alignment appears to be "center-left" alignment, going from some text-alignment strings present in the game's SWIF files and some of my own testing. For this text alignment, the text will be center-aligned when it's single-lined and left-aligned when it's multi-lined.

This appears to be the only new value. Using values such as 5 or 6 produced the same results as left alignment.
